# Generated by Django 3.2.16 on 2023-05-22 21:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squere_first_ten', models.FloatField(verbose_name='Площадь пожара за первые 10 минут')),
                ('squere', models.FloatField(verbose_name='Площадь пожара')),
                ('perimeter', models.FloatField(verbose_name='Периметр пожара')),
                ('front', models.FloatField(verbose_name='Фронт пожара')),
                ('speed_of_squere', models.FloatField(verbose_name='Скорость роста площади пожара')),
                ('line_speed', models.FloatField(verbose_name='Линейная скорость роста пожара')),
                ('front_speed', models.FloatField(verbose_name='Скорость роста фронта пожара')),
                ('object_type', models.CharField(max_length=50, verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Параметры пожара',
                'verbose_name_plural': 'Параметры пожара',
            },
        ),
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название пожара')),
                ('time', models.IntegerField(help_text='Введите время от 1 минуты до 60 минут', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='Время с момента начала пожара')),
                ('corner', models.IntegerField(help_text='Введите значение от 0 градусов до 180 градусов', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(180)], verbose_name='Угол распространения пожара')),
                ('object_type', models.PositiveSmallIntegerField(choices=[(5, 'Склад текстильных изделий'), (10, 'Ремонтный зал ангара'), (8, 'Склад пиломатериалов'), (1, 'Административное здание'), (3, 'Библиотека или торговое предприятие'), (7, 'Склад леса в штабелях'), (6, 'Склад резинотехнических изделий'), (9, 'Типография'), (4, 'Склад льноволокна'), (2, 'Больница или школа')], verbose_name='Объект пожара')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'пожар',
                'verbose_name_plural': 'пожары',
            },
        ),
    ]
