# Generated by Django 3.2.16 on 2023-05-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculate',
            name='corner',
            field=models.IntegerField(default=0, verbose_name='Угол распространения пожара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='calculate',
            name='name',
            field=models.CharField(default=0, max_length=50, verbose_name='Название пожара'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calculate',
            name='time',
            field=models.IntegerField(default=0, verbose_name='Время с момента начала пожара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fire',
            name='description',
            field=models.TextField(blank=True, help_text='Необязательное поле', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='fire',
            name='object_type',
            field=models.PositiveSmallIntegerField(choices=[(3, 'Библиотека или торговое предприятие'), (2, 'Больница или школа'), (4, 'Склад льноволокна'), (7, 'Склад леса в штабелях'), (9, 'Типография'), (5, 'Склад текстильных изделий'), (10, 'Ремонтный зал ангара'), (6, 'Склад резинотехнических изделий'), (1, 'Административное здание'), (8, 'Склад пиломатериалов')], default=1, verbose_name='Объект пожара'),
        ),
    ]
